apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-office-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dental-office-be
  template:
    metadata:
      labels:
        app: dental-office-be
    spec:
      containers:
        - name: dental-office-be
          image: dental-office-be
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret